Traceback (most recent call last):
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kimnielsen/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#import sympy as sym

r = sym.Symbol('r')
A = sym.pi*r**2

# dA = A'*dr

A_prime = sym.diff(A,r,1)

print('The area will change by: dA = '+str(A_prime)+'dr')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m#import sympy as sym[39;00m
[0;32m----> 3[0m r [38;5;241m=[39m [43msym[49m[38;5;241m.[39mSymbol([38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m)
[1;32m      4[0m A [38;5;241m=[39m sym[38;5;241m.[39mpi[38;5;241m*[39mr[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m
[1;32m      6[0m [38;5;66;03m# dA = A'*dr[39;00m

[0;31mNameError[0m: name 'sym' is not defined
NameError: name 'sym' is not defined

