Traceback (most recent call last):
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/kim/anaconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kim/anaconda3/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import random
import numpy as np

dum = 100.*random.random()
digits0 = random.randint(2,5)

# correct answer
answer0 = np.format_float_positional(dum, precision=digits0, unique=False, fractional=False, trim='k')
answer0 = float(answer0)

# wrong sig figs
answer1 = np.format_float_positional(dum, precision=digits0+1, unique=False, fractional=False, trim='k')
answer1 = float(answer1)

# wrong sig figs
answer2 = np.format_float_positional(dum, precision=digits0+2, unique=False, fractional=False, trim='k')
answer2 = float(answer2)

# wrong sig figs
answer2 = np.format_float_positional(dum, precision=digits0+3, unique=False, fractional=False, trim='k')
answer2 = float(answer2)

A = [answer0, answer1, answer2, answer3]

dum = float(dum)
digits0 = float(digits0)
example = [{
        "question": "Report "+str(dum)+" to "+str(int(digits0))+"  significant figures.",
        "type": "multiple_choice",
        "answers": [
            {
                "answer": str(A[3]),
                "correct": False,
                "feedback": "False."
            },
            {
                "answer": str(A[1]),
                "correct": False,
                "feedback": "False."
            },
            {
                "answer": str(A[0]),
                "correct": True,
                "feedback": "Correct."
            },
            {
                "answer": str(A[2]),
                "correct": False,
                "feedback": "False."
            }
        ]
    }]

from jupyterquiz import display_quiz

display_quiz(example)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 23[0m
[1;32m     20[0m answer2 [38;5;241m=[39m np[38;5;241m.[39mformat_float_positional(dum, precision[38;5;241m=[39mdigits0[38;5;241m+[39m[38;5;241m3[39m, unique[38;5;241m=[39m[38;5;28;01mFalse[39;00m, fractional[38;5;241m=[39m[38;5;28;01mFalse[39;00m, trim[38;5;241m=[39m[38;5;124m'[39m[38;5;124mk[39m[38;5;124m'[39m)
[1;32m     21[0m answer2 [38;5;241m=[39m [38;5;28mfloat[39m(answer2)
[0;32m---> 23[0m A [38;5;241m=[39m [answer0, answer1, answer2, [43manswer3[49m]
[1;32m     25[0m dum [38;5;241m=[39m [38;5;28mfloat[39m(dum)
[1;32m     26[0m digits0 [38;5;241m=[39m [38;5;28mfloat[39m(digits0)

[0;31mNameError[0m: name 'answer3' is not defined
NameError: name 'answer3' is not defined

